// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-f3OekwPyD1FjxxPZdc9ozWTPHKWybxw',
    appId: '1:656432546114:web:98ff3cf4ebcc402e00c8db',
    messagingSenderId: '656432546114',
    projectId: 'ezapp-store',
    authDomain: 'ezapp-store.firebaseapp.com',
    storageBucket: 'ezapp-store.appspot.com',
    measurementId: 'G-QST7WC23GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4X9paBasdpQ60sNUxh2pNhY6TWW5MNvw',
    appId: '1:656432546114:android:2780479bd7e8fdf100c8db',
    messagingSenderId: '656432546114',
    projectId: 'ezapp-store',
    storageBucket: 'ezapp-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCVJQUAD_M-aEeUNIyCJEWRFJTbCmvzQs',
    appId: '1:656432546114:ios:5e6f04d8a6ca1eba00c8db',
    messagingSenderId: '656432546114',
    projectId: 'ezapp-store',
    storageBucket: 'ezapp-store.appspot.com',
    iosBundleId: 'com.example.ezapps',
  );
}
